version: '3'

services:
  edge:
    build: ./edge
    container_name: edge
    ports:
      - "8080:80"
    command: /bin/bash -c "envsubst '' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  
  sharder:
    build: ./sharder
    container_name: sharder
    ports:
      - "8888:8888"
    environment:
      - DB_TYPE=mysql+pymysql
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=mysql
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
